services:
  vpn:
    image: linuxserver/wireguard
    container_name: agriable-vpn
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./vpn:/config
    ports:
      - "8000:8000"
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: agriable-app
    network_mode: "service:vpn"
    depends_on:
      - vpn