// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptlsehqsupagemvfzipz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0bHNlaHFzdXBhZ2VtdmZ6aXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1NTczMDksImV4cCI6MjA5MjEzMzMwOX0.CcPIoZWV05JW2MoZnLxn_W7LSWxervmjT4PKQZTSMTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});